"""empty message

Revision ID: 382453063fdb
Revises: 519ebaa19bbf
Create Date: 2024-04-19 17:28:31.258704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382453063fdb'
down_revision = '519ebaa19bbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Conteneur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prix', sa.Float(), nullable=False))
        batch_op.drop_column('fragile')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Conteneur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fragile', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('prix')

    # ### end Alembic commands ###
