"""empty message

Revision ID: 8856e8171ffb
Revises: e61da85d7d5d
Create Date: 2024-03-31 00:27:42.908282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8856e8171ffb'
down_revision = 'e61da85d7d5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Conteneur',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_conteneur', sa.String(length=50), nullable=False),
    sa.Column('largeur', sa.Float(precision=2), nullable=False),
    sa.Column('longueur', sa.Float(precision=2), nullable=False),
    sa.Column('hauteur', sa.Float(precision=2), nullable=False),
    sa.Column('Poid_maximal', sa.Float(precision=2), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('fragile', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('nom', sa.String(length=20), nullable=False),
    sa.Column('prenom', sa.String(length=20), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=20), nullable=True),
    sa.Column('mot_de_passe', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code_enregistrement', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Adresse',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rue', sa.String(length=50), nullable=True),
    sa.Column('code_postal', sa.Integer(), nullable=True),
    sa.Column('pays', sa.String(length=50), nullable=False),
    sa.Column('ville', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=30), nullable=False),
    sa.Column('largeur', sa.Float(precision=5), nullable=False),
    sa.Column('longueur', sa.Float(precision=5), nullable=False),
    sa.Column('hauteur', sa.Float(precision=5), nullable=False),
    sa.Column('poids', sa.Float(precision=5), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('fragile', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Commande',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('date_commande', sa.DateTime(), nullable=False),
    sa.Column('largeur', sa.Float(precision=2), nullable=False),
    sa.Column('longueur', sa.Float(precision=2), nullable=False),
    sa.Column('hauteur', sa.Float(precision=2), nullable=False),
    sa.Column('poids', sa.Float(precision=2), nullable=False),
    sa.Column('adresse', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conteneur_commande',
    sa.Column('conteneur_id', sa.Integer(), nullable=True),
    sa.Column('commande_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commande_id'], ['Commande.id'], ),
    sa.ForeignKeyConstraint(['conteneur_id'], ['Conteneur.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conteneur_commande')
    op.drop_table('Commande')
    op.drop_table('Article')
    op.drop_table('Adresse')
    op.drop_table('User')
    op.drop_table('Conteneur')
    # ### end Alembic commands ###
