"""empty message

Revision ID: 8f9dc9b1b577
Revises: 9ac89b07f709
Create Date: 2024-04-22 16:27:01.370320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9dc9b1b577'
down_revision = '9ac89b07f709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Commande', schema=None) as batch_op:
        batch_op.alter_column('date_creation',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Commande', schema=None) as batch_op:
        batch_op.alter_column('date_creation',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
