"""empty message

Revision ID: 9e71140b41ec
Revises: 
Create Date: 2024-04-16 15:48:52.829102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e71140b41ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Commande', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_creation', sa.DateTime(), nullable=True))
        batch_op.drop_column('date_creation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Commande', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_creation', sa.DATETIME(), nullable=False))
        batch_op.drop_column('date_creation')

    # ### end Alembic commands ###
