"""empty message

Revision ID: a1098b44d91c
Revises: e328ca3c4e5c
Create Date: 2024-04-07 18:55:17.904903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1098b44d91c'
down_revision = 'e328ca3c4e5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Commande', schema=None) as batch_op:
        batch_op.alter_column('numero_commande',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Commande', schema=None) as batch_op:
        batch_op.alter_column('numero_commande',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
