"""empty message

Revision ID: ae74ae964562
Revises: 84a7f93cc49a
Create Date: 2024-04-22 18:09:04.063852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae74ae964562'
down_revision = '84a7f93cc49a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Conteneur', schema=None) as batch_op:
        batch_op.alter_column('date_creation',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Conteneur', schema=None) as batch_op:
        batch_op.alter_column('date_creation',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
