"""empty message

Revision ID: e328ca3c4e5c
Revises: fdec3c215b0a
Create Date: 2024-04-07 17:36:33.803189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e328ca3c4e5c'
down_revision = 'fdec3c215b0a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Commande', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_commande', sa.String(length=20), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint('unique_numero_commande_constraint', ['numero_commande'])  # Nommez la contrainte unique
        batch_op.drop_column('hauteur')
        batch_op.drop_column('poids')
        batch_op.drop_column('quantite')
        batch_op.drop_column('largeur')
        batch_op.drop_column('longueur')
        batch_op.drop_column('adresse')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Commande', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adresse', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('longueur', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('largeur', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('quantite', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('poids', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('hauteur', sa.FLOAT(), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('numero_commande')

    # ### end Alembic commands ###
