"""empty message

Revision ID: fdec3c215b0a
Revises: 33828a5f4f5a
Create Date: 2024-04-06 03:31:45.003907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdec3c215b0a'
down_revision = '33828a5f4f5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('adresse_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adresse_id', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
